<?php

require_once __DIR__ . '/_bootstrap.php';

mobileApiJson(200, 'success', 'Water Billing System mobile API is available.', [
    'version' => 'v1',
    'documentation' => mobileApiBuildAbsoluteUrl('/docs/mobile-api.md'),
    'authentication' => 'Bearer token',
    'endpoints' => [
        'POST /api/mobile/login.php',
        'POST /api/mobile/verify_2fa.php',
        'POST /api/mobile/resend_2fa.php',
        'POST /api/mobile/logout.php',
        'GET /api/mobile/me.php',
        'POST /api/mobile/profile_update.php',
        'POST /api/mobile/change_password.php',
        'GET /api/mobile/dashboard.php',
        'GET /api/mobile/meters.php',
        'GET /api/mobile/complaints.php',
        'POST /api/mobile/complaints.php',
        'GET /api/mobile/bills.php',
        'GET /api/mobile/bill.php?id={bill_id}',
        'POST /api/mobile/request_bill_action.php',
        'GET /api/mobile/payments.php',
        'GET /api/mobile/payment.php?id={payment_id}',
        'GET /api/mobile/statement.php',
        'POST /api/mobile/initiate_payment.php',
        'GET /api/mobile/meter_readings.php',
        'POST /api/mobile/submit_reading.php',
        'GET /api/mobile/admin/customers.php',
        'GET /api/mobile/admin/customer.php?id={customer_id}',
        'GET /api/mobile/admin/bill_detail.php?id={bill_id}',
        'GET /api/mobile/admin/approvals.php',
        'POST /api/mobile/admin/approvals.php',
        'GET /api/mobile/admin/complaints.php',
        'POST /api/mobile/admin/complaints.php',
        'POST /api/mobile/admin/manual_payment.php',
        'GET /api/mobile/admin/search_clients.php',
        'GET /api/mobile/admin/collections.php',
        'GET /api/mobile/admin/onboarding_tracker.php',
    ],
    'openapi' => mobileApiBuildAbsoluteUrl('/docs/mobile-api-openapi.json'),
]);