<?php

require_once __DIR__ . '/_bootstrap.php';

mobileApiJson(200, 'success', 'Water Billing System mobile API is available.', [
    'version' => 'v1',
    'documentation' => mobileApiBuildAbsoluteUrl('/docs/mobile-api.md'),
    'authentication' => 'Bearer token',
    'endpoints' => [
        'POST /api/mobile/login.php',
        'GET /api/mobile/register.php',
        'POST /api/mobile/register.php',
        'POST /api/mobile/verify_2fa.php',
        'POST /api/mobile/resend_2fa.php',
        'POST /api/mobile/logout.php',
        'GET /api/mobile/me.php',
        'POST /api/mobile/profile_update.php',
        'POST /api/mobile/change_password.php',
        'GET /api/mobile/theme.php',
        'POST /api/mobile/theme.php',
        'GET /api/mobile/registration_payment.php',
        'POST /api/mobile/registration_payment.php',
        'GET /api/mobile/dashboard.php',
        'GET /api/mobile/meters.php',
        'GET /api/mobile/complaints.php',
        'POST /api/mobile/complaints.php',
        'GET /api/mobile/bills.php',
        'GET /api/mobile/bill.php?id={bill_id}',
        'POST /api/mobile/request_bill_action.php',
        'GET /api/mobile/payments.php',
        'GET /api/mobile/payment.php?id={payment_id}',
        'GET /api/mobile/payment_status.php?payment_id={payment_id}',
        'GET /api/mobile/statement.php',
        'POST /api/mobile/initiate_payment.php',
        'GET /api/mobile/meter_readings.php',
        'POST /api/mobile/submit_reading.php',
        'GET /api/mobile/admin/customers.php',
        'GET /api/mobile/admin/customer.php?id={customer_id}',
        'GET /api/mobile/admin/bill_detail.php?id={bill_id}',
        'GET /api/mobile/admin/approvals.php',
        'POST /api/mobile/admin/approvals.php',
        'GET /api/mobile/admin/complaints.php',
        'POST /api/mobile/admin/complaints.php',
        'POST /api/mobile/admin/manual_payment.php',
        'GET /api/mobile/admin/demand_notices.php',
        'POST /api/mobile/admin/demand_notices.php',
        'GET /api/mobile/admin/integration_health.php',
        'GET /api/mobile/admin/support_inquiries.php',
        'POST /api/mobile/admin/support_inquiries.php',
        'GET /api/mobile/admin/activity_logs.php',
        'POST /api/mobile/admin/activity_logs.php',
        'GET /api/mobile/admin/system_logs.php',
        'POST /api/mobile/admin/system_logs.php',
        'GET /api/mobile/admin/blog.php',
        'POST /api/mobile/admin/blog.php',
        'GET /api/mobile/admin/accounting_overview.php',
        'POST /api/mobile/admin/accounting_overview.php',
        'GET /api/mobile/admin/accounting_reports.php',
        'GET /api/mobile/admin/accounting_ledger.php',
        'POST /api/mobile/admin/accounting_ledger.php',
        'GET /api/mobile/admin/accounting_budget.php',
        'POST /api/mobile/admin/accounting_budget.php',
        'GET /api/mobile/admin/accounting_transfers.php',
        'POST /api/mobile/admin/accounting_transfers.php',
        'GET /api/mobile/admin/users.php',
        'POST /api/mobile/admin/users.php',
        'GET /api/mobile/admin/staff_users.php',
        'POST /api/mobile/admin/staff_users.php',
        'GET /api/mobile/admin/role_permissions.php',
        'POST /api/mobile/admin/role_permissions.php',
        'GET /api/mobile/admin/customer_locations.php',
        'GET /api/mobile/admin/settings.php',
        'POST /api/mobile/admin/settings.php',
        'GET /api/mobile/admin/terms_conditions.php',
        'POST /api/mobile/admin/terms_conditions.php',
        'GET /api/mobile/admin/payments.php',
        'POST /api/mobile/admin/payments.php',
        'GET /api/mobile/admin/payment_transactions.php',
        'POST /api/mobile/admin/payment_transactions.php',
        'GET /api/mobile/admin/registration_proformas.php',
        'POST /api/mobile/admin/registration_proformas.php',
        'GET /api/mobile/admin/invoicing.php',
        'POST /api/mobile/admin/invoicing.php',
        'GET /api/mobile/admin/bill_correction.php',
        'POST /api/mobile/admin/bill_correction.php',
        'GET /api/mobile/admin/reports.php',
        'POST /api/mobile/admin/reports.php',
        'GET /api/mobile/admin/search_clients.php',
        'GET /api/mobile/admin/collections.php',
        'GET /api/mobile/admin/onboarding_tracker.php',
    ],
    'openapi' => mobileApiBuildAbsoluteUrl('/docs/mobile-api-openapi.json'),
]);